### ISSUE TITLE
pod installation issue

### ISSUE THREAD

**Issue by ripple0328** [balvig/motion-hybrid#2]
when I follow the installation guide, there is issue when I run rake pod:install
ruby: 2.2.0
motion: 3.5
```
Run `bundle install` to install missing gems.
  WARNING! BubbleWrap::HTTP is deprecated and will be removed, see https://github.com/rubymotion/BubbleWrap/issues/308
  WARNING! Switch to a different networking library soon - consider AFNetworking: http://afnetworking.com/
  WARNING! You can use the 'bubble-wrap-http' gem if you need compatibility: https://github.com/rubymotion/BubbleWrap-HTTP
Analyzing dependencies
Pre-downloading: `CRToast` from `git@github.com:cruffenach/CRToast.git`
rake aborted!
Pod::Informative: [!] Unable to find a specification for `FontAwesomeKit`
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:399:in `handle_resolver_error'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:58:in `rescue in resolve'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:53:in `resolve'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:377:in `block in resolve_dependencies'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:375:in `resolve_dependencies'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:58:in `analyze'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:184:in `analyze'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/motion-cocoapods-1.7.0/lib/motion/project/cocoapods.rb:225:in `install!'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/motion-cocoapods-1.7.0/lib/motion/project/cocoapods.rb:348:in `block (2 levels) in <top (required)>'
/Users/qingbo/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/qingbo/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Molinillo::NoSuchDependencyError: Unable to find a specification for `FontAwesomeKit`
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:320:in `find_cached_set'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:108:in `search_for'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:211:in `block in sort_dependencies'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:205:in `each'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:205:in `sort_by'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:205:in `sort_dependencies'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:118:in `block (2 levels) in <class:Resolution>'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:161:in `initial_state'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:78:in `start_resolution'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:54:in `resolve'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/molinillo-0.1.2/lib/molinillo/resolver.rb:40:in `resolve'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:55:in `resolve'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:377:in `block in resolve_dependencies'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:375:in `resolve_dependencies'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:58:in `analyze'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:184:in `analyze'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/motion-cocoapods-1.7.0/lib/motion/project/cocoapods.rb:225:in `install!'
/Users/qingbo/.rvm/gems/ruby-2.2.0/gems/motion-cocoapods-1.7.0/lib/motion/project/cocoapods.rb:348:in `block (2 levels) in <top (required)>'
/Users/qingbo/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/qingbo/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => pod:install
(See full trace by running task with --trace)

WARNING: Automatic dependency detection does not work with motion-support. Turn it off in your Rakefile:

  app.detect_dependencies = false
```

it seems like a dependencies issue, how can I update it?

**Comment by balvig** [comment]
Does running `pod setup` help?

**Comment by ripple0328** [comment]
it works, thank you.

**Comment by balvig** [comment]
Great! Will add it to the docs.
